### ISSUE TITLE
Directions for interpolation does not fit with ArcGIS 10.2.2

### ISSUE THREAD

**Issue by wenzeslaus** [ncsu-geoforall-lab/geospatial-modeling-course#16]
The problem is somewhere around using the interpolation wizard and radial basis function (section _Interpolate surface using Radial Basis Functions_):

> The directions for interpolation using the radial basis function didn’t match the options
> in ArcGIS 10.2.2. I couldn’t find the ‘wizard’ that was mentioned.

Assignment _Spatial interpolation and approximation II_:

http://courses.ncsu.edu/gis582/common/arcgis/interpolation_2.html

**Comment by petrasovaa** [comment]
Outdated
