### ISSUE TITLE
terrain modeling: show how to get the classes from the las file

### ISSUE THREAD

**Issue by petrasovaa** [ncsu-geoforall-lab/geospatial-modeling-course#2]

**Comment by wenzeslaus** [comment]
The "Geomorphometry I: Terrain Modeling" assignment (`terrain_modeling_survey_2013.html`) uses _v.in.lidar_ with `class_filter` and `return_filter`.
- [gis582 version online](https://courses.ncsu.edu/gis582/common/grass/terrain_modeling_survey_2013.html)
- [code](https://github.com/ncsu-osgeorel/geospatial-modeling-course/blob/master/grass/terrain_modeling_survey_2013.html)
