### ISSUE TITLE
Change Jing to something else

### ISSUE THREAD

**Issue by petrasovaa** [ncsu-geoforall-lab/geospatial-modeling-course#27]
Jing allows only swf which is difficult to replay on Ubuntu. Alternatives for Windows:

http://www.hongkiat.com/blog/win-screen-recording-softwares/

**Comment by wenzeslaus** [comment]
Some students use Screencastify Lite (https://www.screencastify.com) which records _WebM/VP8 files with Opus audio_ and _can export recordings as MP4_. Free version (Lite) _records up to 10 minutes per video with an embedded Screencastify logo_.
