### ISSUE TITLE
Reorganize Projects page

### ISSUE THREAD

**Issue by petrasovaa** [ncsu-geoforall-lab/geospatial-modeling-course#31]
- [x]  put instructions first and topics second (or into a separate page)
- [ ] add atmospheric science, meteorology to topics
- [x] split the topics into
    1. applications in science and engineering
    2. development, testing and documentation (encourage MGIST students who are GIST professionals to look at ii)

**Comment by hmitaso** [comment]
add course material update to the ii. development topics - we need student volunteers to update ArcGIS part to Pro and/or ArcGIS online. We can also include a project to develop assignment material in QGIS

**Comment by wenzeslaus** [comment]
The additional topics moved to #45. QGIS updates included.
