### ISSUE TITLE
add handling projections, reprojecting, importing, exporting, creating new location to GRASS assignments

### ISSUE THREAD

**Issue by petrasovaa** [ncsu-geoforall-lab/geospatial-modeling-course#4]
use v.in.proj/r.in proj

**Comment by wenzeslaus** [comment]
Although `r|v.in.proj` can be hopefully used in fall 2015 (in release or with `g.extension`), they anyway does not work (yet?) with lidar data (and 3D rasters and temporal data). And also wrong projections or no projection definitions (typical for LL data) are pretty often. So, one need to know the hard way also.

There is some basic assignment in the Clinic (http://courses.ncsu.edu/gis582/common/media/GRASS_clinic2013/NewLocCSTransfGRASS.html). We can also try to fix the manual instead (http://grass.osgeo.org/grass70/manuals/helptext.html). There is few screenshots of location wizard on GRASS Wiki (http://grasswiki.osgeo.org/wiki/GRASS_Location_Wizard) as well as several import-related pages (e.g., http://grasswiki.osgeo.org/wiki/HOWTO_import_SRTM_elevation_data, http://grasswiki.osgeo.org/wiki/Importing_data). A useful approach can be found also on Appropedia (http://www.appropedia.org/A_transition_from_ArcGIS_to_open_source_GIS_softwares).

**Comment by hmitaso** [comment]
I have some related material for the new grassbook (including the associated external data and going through almost all options in location wizard). 
I will try to give it to you before I leave. Fixing the manual would be helpful too.

Helena

> On May 10, 2015, at 11:40 PM, Vaclav Petras notifications@github.com wrote:
> 
> Although r|v.in.proj can be hopefully used in fall 2015 (in release or with g.extension), they anyway does not work (yet?) with lidar data (and 3D rasters and temporal data). And also wrong projections or no projection definitions (typical for LL data) are pretty often. So, one need to know the hard way also.
> 
> There is some basic assignment in the Clinic (http://courses.ncsu.edu/gis582/common/media/GRASS_clinic2013/NewLocCSTransfGRASS.html). We can also try to fix the manual instead (http://grass.osgeo.org/grass70/manuals/helptext.html). There is few screenshots of location wizard on GRASS Wiki (http://grasswiki.osgeo.org/wiki/GRASS_Location_Wizard) as well as several import-related pages (e.g., http://grasswiki.osgeo.org/wiki/HOWTO_import_SRTM_elevation_data, http://grasswiki.osgeo.org/wiki/Importing_data). A useful approach can be found also on Appropedia (http://www.appropedia.org/A_transition_from_ArcGIS_to_open_source_GIS_softwares).
> 
> —
> Reply to this email directly or view it on GitHub.

Helena Mitasova
Professor at the Department of Marine, 
Earth, and Atmospheric Sciences
and Center for Geospatial Analytics
North Carolina State University
Raleigh, NC 27695-8208
hmitaso@ncsu.edu
http://geospatial.ncsu.edu/osgeorel/
"All electronic mail messages in connection with State business which are sent to or received by this account are subject to the NC Public Records Law and may be disclosed to third parties.”

**Comment by wenzeslaus** [comment]
We can use r.import and v.import in addons:
- http://grass.osgeo.org/grass70/manuals/addons/r.import.html
- http://grass.osgeo.org/grass70/manuals/addons/v.import.html

Unfortunately, these don't work with lidar data, so for lidar, one still need to go the hard way.

Also, both miss the -o flag to ignore/override the dataset projection and use the current location's projection (good for lidar data with broken projection).

**Comment by wenzeslaus** [comment]
_r.import_ and _v.import_ are included in 7.0.2 but missing `-o` (_r.in.gdal_ and _v.in.ogr_ required) and lidar data reprojection (_r.proj_ and _v.proj_ required) are still an issue for student projects. Some new material is needed in any case.
- https://grass.osgeo.org/grass70/manuals/r.import.html
- https://grass.osgeo.org/grass70/manuals/v.import.html

**Comment by wenzeslaus** [comment]
In efca062 and 1348c92 I added `projections.html`, now renamed to `import.html` which discusses importing with different projections and it also mentions _v.proj_ and _r.proj_ (without examples). It also discusses _r.in.lidar_ and _v.in.lidar_ and _las2las_.  This should be useful for projects. It is linked from the `grass/data_acquisition.html` page (first assignment). This assignment also links to a new manual page about [GRASS database structure](http://grass.osgeo.org/grass71/manuals/grass_database.html).

Also, 7.0.3 has the `-o` flags for _r.import_ and _v.import_. So we can completely migrate to these in the instructions.

We are still missing location creation/wizard. So, leaving this open until we decide what to do.

Source code:
https://github.com/ncsu-osgeorel/geospatial-modeling-course/blob/master/grass/import.html

Online:
http://ncsu-osgeorel.github.io/geospatial-modeling-course/grass/import.html

**Comment by petrasovaa** [comment]
We need to incorporate setting up new location in data acquisition:
http://ncsu-geoforall-lab.github.io/geospatial-modeling-course/grass/data_acquisition.html

ideally somewhere else too

**Comment by petrasovaa** [comment]
Fixed in 41a77c686def4011ce2eb29f45331e58ed904be7 and 1bd6fd903f0776dc4ac4fdfe83f6caec6f5145bd
