### ISSUE TITLE
Slope Symbology

### ISSUE THREAD

**Issue by c-leigh-2** [ncsu-geoforall-lab/geospatial-modeling-course#55]
I'm currently working on coding a slope tool in ArcGIS Pro that works with a raster dataset. Ideally, I would create a new raster dataset that would perform a calculation on each pixel in the raster and output the result to the same location on the grid of a new raster. 

ArcGIS Pro has a tool that does this, but is outputting contour lines with null values between them as opposed to a complete raster dataset with values at each pixel location. Has anyone done this, or does anyone have any advice as to how I can find the code for this slope tool in order to alter it so I can achieve the result I'm looking for?

New to this community - any help is appreciated! Thank you!

**Comment by wenzeslaus** [comment]
Hi, this repository contains [open education](https://en.wikipedia.org/wiki/Open_education) resources for a course taught at [NC State University](https://cnr.ncsu.edu/geospatial/academics/courses/) (which you might be able to [take separately](https://online-distance.ncsu.edu/admissions/non-degree-seeking/)).

You may want to ask your question at [GIS StackExchange](https://gis.stackexchange.com/). I suggest you go through this [Raster terrain analysis](https://docs.qgis.org/3.22/en/docs/user_manual/processing_algs/qgis/rasterterrainanalysis.html) guide in [QGIS](https://qgis.org/).
